import "@/app/ui/globals.css";
import Appbar from "./ui/appbar";
import { InitColorSchemeScript } from "@mui/material";
import Wrapper from "./ui/wrapper";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
export const metadata = {
  title: "Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppRouterCacheProvider>
          <InitColorSchemeScript attribute="class" />
          <Wrapper>
            <Appbar />
            {children}
          </Wrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
