import "@/app/ui/globals.css";
import Appbar from "./ui/appbar";
import { Box } from "@mui/material";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Appbar />
        <Box>{children}</Box>
      </body>
    </html>
  );
}
