import "@/app/ui/globals.css";
import Appbar from "./ui/appbar";
import { Box } from "@mui/material";
import { cookies } from "next/headers";
export const metadata = {
  title: "Demo",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const isLoggedIn = cookieStore.has("token");
  return (
    <html lang="en">
      <body>
        <Appbar isLoggedIn={isLoggedIn} />
        <Box>{children}</Box>
      </body>
    </html>
  );
}
